### ISSUE TITLE
[Minor] Couldn't activate virtual environment as instructed

### ISSUE THREAD

**Issue by MeHappyLucky** [21Gxme/ku-polls#61]
After following the instruction, there's a problem with activating virtual environment.
On Window, I couldn't run `.venv\Scripts\activate.bat` after `python -m venv venv`
In Pycharm, `venv\Scripts\activate.bat` (without dot) seemingly does nothing, but `venv\Scripts\activate` works just fine
In Command Prompt, `venv\Scripts\activate.bat` (without dot), works just fine

Environment Information:
Python 3.9.7
Window 11

**Comment by 21Gxme** [comment]
Ok, I fixed it now.
